packages:
  # specify a package in a direct subdir of the root
  - 'src'
  # all packages in direct subdirs of packages/
  - 'reactive-graph-backend/**'
  - 'reactive-graph-frontend/**'
  # exclude packages that are inside test directories
  - '!**/test/**'